In [1]:
#THIS NOTEBOOK CREATES THE TAGS AND THE BINARY ARRAYS FROM A CSV DATASET
import numpy as np
import pandas as pd

# Read in the CSV file
csv_file = '../data_final/spotify_data_downloaded_songs.csv'
df = pd.read_csv(csv_file, index_col=0)
df = df.drop(['artist_name','track_uri','track_name', 'name','track_href','tempo','genres'], axis=1)
# Get the column names of the DataFrame
column_names = df.columns.tolist()

# Convert the column names to a NumPy array
np_array = np.array(column_names)
print("How many columns we have in the end: ",len(np_array))
# Save the NumPy array to a file
np.save('../data_final/tags.npy', np_array)

np_array = df.to_numpy()
# Save the NumPy array to a file
np.save('../data_final/binary.npy', np_array)
print(np_array)


How many columns we have in the end:  32
[[1 0 0 ... 0 1 0]
 [1 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]]


In [4]:
#THIS NOTEBOOK SPLITS A CSV DATASET INTO TRAIN, TEST AND VALIDATION PARTITIONS, and saves them as numpys
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# Load the CSV file
#df = pd.read_csv('../our_data/spotify_data_final.csv', index_col=0, usecols=['track_uri'])
csv_file = '../data_final/spotify_data_downloaded_songs.csv'
df = pd.read_csv(csv_file, index_col=0)

# Reset the index
df = df.reset_index(drop=True)


# Add a column to the original data to store the original row index
df['dataset_index'] = df.index

# Split the data into training and testing sets (80% for training, 20% for testing)
train_data, test_data = train_test_split(df, test_size=0.2, random_state=42)

# Split the training data into training and validation sets (80% for training, 20% for validation)
train_data, val_data = train_test_split(train_data, test_size=0.2, random_state=42)

train_data = train_data.loc[:, ['dataset_index', 'track_uri']]
test_data = test_data.loc[:, ['dataset_index', 'track_uri']]
val_data = val_data.loc[:, ['dataset_index', 'track_uri']]

# Save the data to new CSV files
train_data.to_csv('../data_final/train.csv', index=False)
test_data.to_csv('../data_final/test.csv', index=False)
val_data.to_csv('../data_final/val.csv', index=False)